function [kb, kfree, z2pred, wsum] = bound_wavenumber_spectral(f, S, h, g)
% BOUND_WAVENUMBER_SPECTRAL  Expected bound wavenumber at each frequency, from the
% full spectral shape. No peak frequency, no band definition, no reference.
%
%   [kb, kfree, z2pred, wsum] = bound_wavenumber_spectral(f, S, h, g)
%
% WHY THIS EXISTS. Every harmonic-band diagnostic in this project has so far been
% defined relative to a peak frequency -- "the band at 2*fp". That is unsafe here:
% O'Reilly et al. (2016) show fp is unstable in southern California when sea and
% swell peak energies are comparable, and 24.7% of our hours are in exactly that
% regime (analyze_harmonic_band_l2.m). Worse, a swell peak at 0.075 Hz puts its
% harmonic at 0.15 Hz, which lies INSIDE the sea band, so "the band at 2*fp"
% conflates bound swell harmonic with genuine sea energy. Swapping argmax fp for
% another peak estimator does not fix that; a centroid is worse, because the sea
% drags it upward and mis-locates the harmonic.
%
% THE IDEA. "Boundness" is a property of each frequency, not of a distance from a
% peak. A bound component at frequency f is generated by triads (f1, f-f1) and
% carries wavenumber k(f1) + k(f-f1) -- NOT the free-wave k(f). Weighting each
% contributing pair by its energy S(f1)S(f-f1), as the second-order interaction
% does at leading order, gives an expected bound wavenumber at every f:
%
%   kb(f) = sum_f1 [ k(f1) + k(f-f1) ] S(f1) S(f-f1) / sum_f1 S(f1) S(f-f1)
%
% This uses the WHOLE spectrum. Mixed sea/swell is handled automatically, because
% swell-swell, swell-sea and sea-sea pairs each enter with their actual energy.
%
% EFFICIENT FORM. Substituting f1 -> f-f1 maps the k(f-f1) term onto the k(f1)
% term with identical weight, since S(f1)S(f-f1) is symmetric. Hence
%
%   kb = 2 * conv(k.*S, S) / conv(S, S)
%
% two discrete convolutions rather than a double loop.
%
% WHAT IT IS FOR. Combined with the pressure-velocity impedance
% z^2(f) = (k_free(f)/kappa(f))^2 (see L2_spectral/test_kp_bound_harmonic.m), it
% gives the fully bound prediction at every frequency,
%
%   z2pred(f) = ( k_free(f) / kb(f) )^2
%
% from which the bound fraction follows by the reciprocal inversion
%   beta(f) = (1 - 1/z2_obs) / (1 - 1/z2pred).
%
% SANITY LIMIT (asserted in the test). For a monochromatic primary at f0 the only
% pair summing to 2*f0 is (f0, f0), so kb(2 f0) = 2 k(f0) exactly -- recovering the
% classical bound-harmonic wavenumber as a special case of the general formula.
%
% SCOPE. Sum interactions only (f1 + f2 = f), i.e. super-harmonics. Difference
% interactions, which generate bound infragravity energy, are a separate
% calculation and are not included here.
%
% INPUTS
%   f - frequency vector, uniformly spaced, ascending, f(1) >= 0 [nf x 1] (Hz)
%   S - spectral density on that grid [nf x 1]. Non-finite values treated as 0.
%   h - water depth (m)
%   g - gravity (m/s^2), default 9.81
%
% OUTPUTS
%   kb     - energy-weighted expected bound wavenumber at each f (rad/m).
%            NaN where no contributing pair carries weight.
%   kfree  - free-wave wavenumber at each f (rad/m)
%   z2pred - (kfree./kb).^2, the fully-bound z^2 prediction at each f
%   wsum   - total pair weight at each f, i.e. conv(S,S). Use it to mask
%            frequencies where the prediction rests on negligible energy.
%
% REQUIRES get_wavenumber.m
%
% Author: Holden Leslie-Bole, 2026

% g is accepted for interface consistency with the callers but is NOT used: the
% wavenumber comes from get_wavenumber.m, which hardcodes g = 9.81 internally.
% Passing a different g here would silently have no effect, so it is named and
% ignored deliberately rather than plumbed through to nowhere.
if nargin < 4, g = 9.81; end %#ok<NASGU>

f = f(:); S = S(:);
nf = numel(f);
if nf < 4 || numel(S) ~= nf
    error('bound_wavenumber_spectral:size','f and S must be equal-length vectors.');
end
df = median(diff(f));
if ~isfinite(df) || df <= 0
    error('bound_wavenumber_spectral:grid','f must be uniformly spaced and ascending.');
end

S(~isfinite(S)) = 0;
S(S < 0) = 0;

kfree = zeros(nf,1);
pos = f > 0;
kfree(pos) = get_wavenumber(2*pi*f(pos), h);

% conv(S,S) and conv(k.*S, S). Index arithmetic: with f starting at f(1), the
% convolution output index m corresponds to frequency 2*f(1) + (m-1)*df, so the
% element matching target frequency f(j) sits at m = j - (f(1)/df) + 1... which is
% only integral when f(1) is a multiple of df. Handle the general case by
% interpolating the convolution onto the target grid, which is exact when the grid
% starts at 0 or at an integer multiple of df.
c_SS = conv(S, S) * df;
c_kS = conv(kfree .* S, S) * df;
fconv = 2*f(1) + (0:(2*nf-2))' * df;

wsum = interp1(fconv, c_SS, f, 'linear', 0);
num  = interp1(fconv, c_kS, f, 'linear', 0);

kb = 2 * num ./ wsum;
kb(~isfinite(kb) | wsum <= 0) = NaN;

z2pred = (kfree ./ kb).^2;
z2pred(~isfinite(z2pred)) = NaN;
end
