function gs = site_grain_size(site)
% SITE_GRAIN_SIZE  Per-site grain-size statistics for inner-shelf instrument sites.
%
%   gs = site_grain_size('MOP586_5m')
%
%   Returns struct with fields (all sizes in METERS):
%     D16, D50, D84, D90   - percentile grain diameters
%     sorting              - geometric sorting sigma = sqrt(D84/D16)
%     source               - measurement origin / file
%     date                 - sampling date (YYYY-MM or '')
%     status               - 'measured' | 'extrapolated' | 'assumed_default'
%     notes                - caveat / context
%
% MEASURED entries are from a Fritsch Analysette 22 NanoTec LPA on subaqueous
% grab samples (TBR23, May/Jun 2023; analyzed 28 June 2023). The Fritsch was
% the lab's LPA before the BetterSizer S3 Plus was acquired in 2024; post-2024
% samples will use the BetterSizer (update this header when that data lands).
% D50 uses the PDF-canonical median (instrument internal calc); D84/D90/D16
% are log-linear interpolations on the 10-bin Q3 CDF in the LPA Excel, scaled
% by (PDF_D50 / interp_D50) so all percentiles are internally consistent.
%
% EXTRAPOLATED entries follow the MOP586 cross-shore D50 fining trend
% (5m -> 7m: 268 -> 228 um, ~17% finer per 2m depth; log-linear extrapolation)
% with sorting fixed at the 7m value. Update with measured values when LPA
% samples become available.
%
% ASSUMED_DEFAULT entries (Solana, SIO) are placeholder regional values from
% MOP586 7m until site-specific LPA is collected.
%
% USAGE
%   gs = site_grain_size('MOP586_5m');
%   ks = 2.5 * gs.D84;                  % Wiberg-Smith roughness
%   [tau_b, fw, Aw] = bed_stress_ks(Ub, Tp, ks, rho);
%
% TO ADD A NEW SAMPLE: append an entry to T below (status='measured'),
% replacing or augmenting the matching extrapolation.
%
% Author: Holden Leslie-Bole, 2026-05-23 (Paper 2 audit of bed-stress methods)

% --- MEASURED: TBR23 subaqueous, June 2023 (BetterSizer, n=3-6 reps) ---
T = struct('site',{},'D16',{},'D50',{},'D84',{},'D90',{},'sorting',{}, ...
           'source',{},'date',{},'status',{},'notes',{});

T(end+1) = struct( ...
    'site','MOP580_5m', ...
    'D16', 153e-6, 'D50', 320e-6, 'D84', 730e-6, 'D90', 898e-6, 'sorting', 2.18, ...
    'source','Fritsch Analysette 22 NanoTec LPA, "Torrey Pines LPA Data 2023.xls" (6 reps, "5 south" a+b)', ...
    'date','2023-05', 'status','measured', ...
    'notes','BIMODAL: main mode ~300um + clear second mode ~600-1000um; coarse tail 9% >1mm; SD 102% of D50');

T(end+1) = struct( ...
    'site','MOP586_5m', ...
    'D16', 147e-6, 'D50', 268e-6, 'D84', 428e-6, 'D90', 465e-6, 'sorting', 1.71, ...
    'source','Fritsch Analysette 22 NanoTec LPA, "Torrey Pines LPA Data 2023.xls" (3 reps, "5 north")', ...
    'date','2023-05', 'status','measured', ...
    'notes','Moderately sorted main mode + 2.6% coarse tail >1mm');

T(end+1) = struct( ...
    'site','MOP586_7m', ...
    'D16', 142e-6, 'D50', 228e-6, 'D84', 412e-6, 'D90', 460e-6, 'sorting', 1.71, ...
    'source','Fritsch Analysette 22 NanoTec LPA, "Torrey Pines LPA Data 2023.xls" (3 reps, "7 north")', ...
    'date','2023-05', 'status','measured', ...
    'notes','Narrow main mode + 1.8% coarse tail >1mm');

% --- EXTRAPOLATED: MOP586 cross-shore fining trend, no measurement yet ---

T(end+1) = struct( ...
    'site','MOP586_10m', ...
    'D16', 110e-6, 'D50', 179e-6, 'D84', 311e-6, 'D90', 348e-6, 'sorting', 1.68, ...
    'source','log-linear extrapolation of MOP586 5m/7m D50 trend', ...
    'date','', 'status','extrapolated', ...
    'notes','NO LPA SAMPLE. Assumed D50 from log-linear (5m=268, 7m=228) -> 10m=179um. Sorting = 7m value. REPLACE WITH MEASURED when available.');

T(end+1) = struct( ...
    'site','MOP586_15m', ...
    'D16', 75e-6, 'D50', 120e-6, 'D84', 208e-6, 'D90', 233e-6, 'sorting', 1.68, ...
    'source','log-linear extrapolation of MOP586 5m/7m D50 trend', ...
    'date','', 'status','extrapolated', ...
    'notes','NO LPA SAMPLE. Assumed D50 from log-linear extrap to 15m -> 120um. Sorting = 7m. REPLACE WITH MEASURED.');

T(end+1) = struct( ...
    'site','MOP580_7m', ...
    'D16', 142e-6, 'D50', 228e-6, 'D84', 412e-6, 'D90', 460e-6, 'sorting', 1.71, ...
    'source','assumed same as MOP586_7m (no LPA at MOP580 7m)', ...
    'date','', 'status','extrapolated', ...
    'notes','NO LPA SAMPLE at "7 south". Used MOP586_7m values. Alongshore variation at 5m (268 vs 320) suggests +/-20% uncertainty. REPLACE WITH MEASURED.');

% --- ASSUMED_DEFAULT: other altimeter sites, no LPA ---

T(end+1) = struct( ...
    'site','MOP654_7m', ...           % Solana Beach
    'D16', 142e-6, 'D50', 228e-6, 'D84', 412e-6, 'D90', 460e-6, 'sorting', 1.71, ...
    'source','assumed_default = MOP586_7m (no Solana LPA)', ...
    'date','', 'status','assumed_default', ...
    'notes','SOLANA: no LPA. Used Torrey 7m as regional default. Different site morphology (Cardiff cell, more shell hash near Tabletops headland) may give meaningfully different grain size. PRIORITY for new sampling.');

T(end+1) = struct( ...
    'site','MOP511_6m', ...           % SIO Pier
    'D16', 147e-6, 'D50', 268e-6, 'D84', 428e-6, 'D90', 465e-6, 'sorting', 1.71, ...
    'source','assumed_default = MOP586_5m (no SIO LPA)', ...
    'date','', 'status','assumed_default', ...
    'notes','SIO Pier: no LPA. Used Torrey 5m. SIO bed is canyon-influenced; may have finer/coarser tail. PRIORITY for new sampling.');

% --- Look up ---
found = strcmp({T.site}, site);
if ~any(found)
    valid = strjoin({T.site}, ', ');
    error('site_grain_size:unknown', ...
        'No grain-size entry for site "%s". Available: %s. Add a new entry to site_grain_size.m.', ...
        site, valid);
end
gs = T(find(found, 1));
end
