% copy_to_server.m
% Author: Holden Leslie-Bole, 2026
% Copy L2 and L3 processed .mat files to the group server, organized
% deployment-first under Processed_HLB. Generates README.md and
% manifest.csv. Idempotent — re-running refreshes all artifacts.

src_root  = '/Users/holden/Documents/Scripps/Research/PUV_Pipeline/outputs';
dest_root = '/Volumes/group/PUV_data/Vector/Processed_HLB';

if ~isfolder(fileparts(dest_root))
    error('Server not mounted: %s', fileparts(dest_root));
end
if ~exist(dest_root, 'dir'); mkdir(dest_root); end

[~, git_hash] = system('cd /Users/holden/Documents/Scripps/Research/PUV_Pipeline && git rev-parse --short HEAD');
git_hash = strtrim(git_hash);

%% Collect L2 and L3 files
L2_files = dir(fullfile(src_root, 'L2', '*', '*_L2.mat'));
L3_files = dir(fullfile(src_root, 'L3', '*', '*_L3.mat'));
fprintf('Found %d L2 files, %d L3 files\n', numel(L2_files), numel(L3_files));

%% Build manifest while copying
rows = {};
all_files = [arrayfun(@(s) struct('level','L2','d',s), L2_files); ...
             arrayfun(@(s) struct('level','L3','d',s), L3_files)];

for k = 1:numel(all_files)
    level = all_files(k).level;
    d     = all_files(k).d;
    deployment = regexp(d.folder, [filesep '([^' filesep ']+)$'], 'tokens', 'once');
    deployment = deployment{1};

    src_path = fullfile(d.folder, d.name);
    dest_dir = fullfile(dest_root, deployment, sprintf('Level%s_QC', level(2)));
    if ~exist(dest_dir, 'dir'); mkdir(dest_dir); end
    dest_path = fullfile(dest_dir, d.name);

    % Read metadata from local copy (fast)
    instr = regexprep(d.name, ['_' level '\.mat$'], '');
    depth_m = NaN;
    tok = regexp(instr, '_([0-9]+)m', 'tokens', 'once');
    if ~isempty(tok); depth_m = str2double(tok{1}); end

    t_start = NaT; t_end = NaT; n_seg = NaN; n_valid = NaN;
    try
        m = matfile(src_path);
        S = whos(m);
        topvar = S(1).name;
        if any(strcmp({S.name}, level)); topvar = level; end
        Sd = m.(topvar);
        if isfield(Sd, 'time') && ~isempty(Sd.time)
            t_start = Sd.time(find(~isnat(Sd.time), 1, 'first'));
            t_end   = Sd.time(find(~isnat(Sd.time), 1, 'last'));
            n_seg   = numel(Sd.time);
        end
        if isfield(Sd, 'segValid'); n_valid = sum(Sd.segValid); end
    catch ME
        fprintf('  [warn] could not read metadata from %s: %s\n', d.name, ME.message);
    end

    % Copy
    fprintf('[%3d/%3d] %s/%s/%s ... ', k, numel(all_files), deployment, ...
            sprintf('Level%s_QC', level(2)), d.name);
    t0 = tic;
    copyfile(src_path, dest_path);
    fprintf('%.1fs (%.1f MB)\n', toc(t0), d.bytes/1e6);

    rows(end+1, :) = {deployment, level, instr, depth_m, ...
                      string(t_start), string(t_end), n_seg, n_valid, ...
                      round(d.bytes/1e6, 1)};                              %#ok<SAGROW>
end

%% Manifest
T = cell2table(rows, 'VariableNames', ...
    {'deployment','level','instrument','depth_m', ...
     'time_start','time_end','n_segments','n_valid','size_MB'});
T = sortrows(T, {'deployment','level','instrument'});
writetable(T, fullfile(dest_root, 'manifest.csv'));
fprintf('\nWrote manifest.csv (%d rows)\n', height(T));

%% README.md
readme = sprintf([ ...
    '# PUV Vector Processed Data — Holden Leslie-Bole\n\n' ...
    'Processed Nortek Vector PUV data from %d deployments along the San Diego coast.\n' ...
    'Generated: %s.\n\n' ...
    '## Source\n\n' ...
    'Pipeline: https://github.com/holdenlesliebole/Nortek_Vector_PUV_Pipeline\n' ...
    'Commit: %s\n\n' ...
    '## Levels\n\n' ...
    '- **Level2_QC** — Spectral analysis on 17-min segments (2048 samples @ 2 Hz):\n' ...
    '  multi-taper PSD (DPSS, NW=4, K=7), surface elevation spectrum S_eta(f),\n' ...
    '  bulk wave parameters (Hs, Tp, mean direction, spread), directional Fourier\n' ...
    '  coefficients (a1, b1, a2, b2), Z-test, radiation stress.\n' ...
    '- **Level3_QC** — Forcing-derived quantities: energy partitioning by frequency\n' ...
    '  band, bed velocity / stress, Shields parameter, Rouse number, MOP shoaled\n' ...
    '  reference, currents.\n\n' ...
    'L1 (QC''d raw time series) is regenerable from raw data + this pipeline and\n' ...
    'is not included here to keep the share size manageable.\n\n' ...
    '## Layout\n\n' ...
    '```\n' ...
    'Processed_HLB/\n' ...
    '  README.md\n' ...
    '  manifest.csv      — per-file index (deployment, instrument, depth, time range, sizes)\n' ...
    '  <deployment>/\n' ...
    '    Level2_QC/      — *_L2.mat\n' ...
    '    Level3_QC/      — *_L3.mat\n' ...
    '```\n\n' ...
    '## Conventions\n\n' ...
    '- Coordinate system: x cross-shore (positive onshore), y alongshore (positive north)\n' ...
    '- Vertical: NAVD88 (MSL = 0.774 m, MHW = 1.344 m)\n' ...
    '- Times: UTC, datetime\n' ...
    '- File naming: `<MOP_or_site>_<depth>m_L<N>.mat` (e.g., MOP580_7m_L2.mat)\n\n' ...
    '## Ruby2D note\n\n' ...
    'Ruby2D contains a Level2 reprocess of the legacy archived L1 file using the\n' ...
    'multi-taper pipeline, used for the head-to-head validation in\n' ...
    '`docs/pipeline_comparison_legacy.md` (in the source repo). It is not a new\n' ...
    'deployment.\n\n' ...
    '## Contact\n\n' ...
    'Holden Leslie-Bole <hlesliebole@ucsd.edu>, Scripps Institution of Oceanography.\n'], ...
    numel(unique(T.deployment)), datestr(now, 'yyyy-mm-dd'), git_hash);
fid = fopen(fullfile(dest_root, 'README.md'), 'w'); fprintf(fid, '%s', readme); fclose(fid);
fprintf('Wrote README.md\n');

%% Ruby2D-specific README
ruby_dir = fullfile(dest_root, 'Ruby2D');
if exist(ruby_dir, 'dir')
    ruby_readme = sprintf([ ...
        '# Ruby2D — multi-taper reprocess (not a new deployment)\n\n' ...
        'This folder contains a Level2 reprocess of the archived legacy L1 file\n' ...
        '`Torrey_Ruby2D_582_6m_processed.mat` using the multi-taper pipeline\n' ...
        '(commit %s). It exists for the head-to-head validation against the\n' ...
        'legacy archived L2; see `docs/pipeline_comparison_legacy.md` and\n' ...
        '`docs/multitaper_writeup.pdf` in the source repo.\n\n' ...
        'For Ruby2D L1 and the original L2, see `/Volumes/group/Ruby2D/PUV/`.\n'], ...
        git_hash);
    fid = fopen(fullfile(ruby_dir, 'README.md'), 'w'); fprintf(fid, '%s', ruby_readme); fclose(fid);
    fprintf('Wrote Ruby2D/README.md\n');
end

%% Summary
total_bytes = sum(T.size_MB);
fprintf('\nDone. %d files, %.1f MB total, %d deployments.\n', ...
    height(T), total_bytes, numel(unique(T.deployment)));
fprintf('Destination: %s\n', dest_root);
