% refresh_manifest.m
% Re-read metadata for newly-pushed/changed files on the server,
% merge into the existing manifest, and rewrite manifest.csv + README.md.
% Targeted refresh (no re-copying); files must already be in place.
% Author: Holden Leslie-Bole, 2026

dest_root = '/Volumes/group/PUV_data/Vector/Processed_HLB';
manifest_path = fullfile(dest_root, 'manifest.csv');

[~, git_hash] = system('cd /Users/holden/Documents/Scripps/Research/PUV_Pipeline && git rev-parse --short HEAD');
git_hash = strtrim(git_hash);

% Files whose metadata we need to refresh (added or changed since last manifest)
to_refresh = { ...
    'IB18W', 'L2', 'MOP045_7m'; ...
    'IB18W', 'L2', 'MOP055_7m'; ...
    'IB19S', 'L2', 'MOP045_7m'; ...
    'IB19S', 'L2', 'MOP055_7m'; ...
    'IB18W', 'L3', 'MOP045_7m'; ...
    'IB18W', 'L3', 'MOP055_7m'; ...
    'IB19S', 'L3', 'MOP045_7m'; ...
    'IB19S', 'L3', 'MOP055_7m'; ...
    'RUBY22','L2', 'MOP578_10m'; ...
    'RUBY22','L2', 'MOP579_6m'; ...
    'RUBY22','L2', 'MOP582_30m'; ...
    'RUBY22','L3', 'MOP578_10m'; ...
    'RUBY22','L3', 'MOP579_6m'; ...
    'RUBY22','L3', 'MOP582_30m'; ...
};

T = readtable(manifest_path, 'TextType','string');

for k = 1:size(to_refresh,1)
    dep = to_refresh{k,1};
    level = to_refresh{k,2};
    instr = to_refresh{k,3};

    fpath = fullfile(dest_root, dep, sprintf('Level%s_QC', level(2)), [instr '_' level '.mat']);
    if ~exist(fpath, 'file')
        warning('Missing: %s', fpath); continue
    end
    info = dir(fpath);

    depth_m = NaN;
    tok = regexp(instr, '_([0-9]+)m', 'tokens', 'once');
    if ~isempty(tok); depth_m = str2double(tok{1}); end

    t_start = NaT; t_end = NaT; n_seg = NaN; n_valid = NaN;
    try
        m = matfile(fpath);
        S = whos(m);
        topvar = S(1).name;
        if any(strcmp({S.name}, level)); topvar = level; end
        Sd = m.(topvar);
        if isfield(Sd, 'time') && ~isempty(Sd.time)
            t_start = Sd.time(find(~isnat(Sd.time), 1, 'first'));
            t_end   = Sd.time(find(~isnat(Sd.time), 1, 'last'));
            n_seg   = numel(Sd.time);
        end
        if isfield(Sd, 'segValid'); n_valid = sum(Sd.segValid); end
    catch ME
        fprintf('  [warn] %s/%s/%s: %s\n', dep, level, instr, ME.message);
    end

    new_row = {string(dep), string(level), string(instr), depth_m, ...
               string(t_start), string(t_end), n_seg, n_valid, ...
               round(info.bytes/1e6, 1)};

    idx = find(T.deployment == dep & T.level == level & T.instrument == instr, 1);
    if isempty(idx)
        T = [T; cell2table(new_row, 'VariableNames', T.Properties.VariableNames)]; %#ok<AGROW>
        fprintf('  + %s/%s/%s\n', dep, level, instr);
    else
        T(idx,:) = cell2table(new_row, 'VariableNames', T.Properties.VariableNames);
        fprintf('  ~ %s/%s/%s\n', dep, level, instr);
    end
end

T = sortrows(T, {'deployment','level','instrument'});
writetable(T, manifest_path);
fprintf('\nWrote %s (%d rows, %d deployments)\n', manifest_path, height(T), numel(unique(T.deployment)));

%% README
readme = sprintf([ ...
    '# PUV Vector Processed Data — Holden Leslie-Bole\n\n' ...
    'Processed Nortek Vector PUV data from %d deployments along the San Diego coast.\n' ...
    'Generated: %s.\n\n' ...
    '## Source\n\n' ...
    'Pipeline: https://github.com/holdenlesliebole/Nortek_Vector_PUV_Pipeline\n' ...
    'Commit: %s\n\n' ...
    '## Levels\n\n' ...
    '- **Level2_QC** — Spectral analysis on 1-hour segments (7200 samples @ 2 Hz):\n' ...
    '  multi-taper PSD (DPSS, NW=4, K=7), surface elevation spectrum S_eta(f),\n' ...
    '  bulk wave parameters (Hs, Tp, mean direction, spread), directional Fourier\n' ...
    '  coefficients (a1, b1, a2, b2), Z-test, radiation stress, segment-mean\n' ...
    '  cross-shore and alongshore velocity (uMean, vMean) for mean-flow analysis.\n' ...
    '  (Switched from 17-min to 1-hour default in May 2026; the legacy 17-min L2\n' ...
    '  archive is at `/Volumes/group/PUV_data/Vector/Processed_HLB_17min/` if\n' ...
    '  needed for reproducibility of the May 2026 mean-flow validation paper.)\n' ...
    '- **Level3_QC** — Forcing-derived quantities: energy partitioning by frequency\n' ...
    '  band, bed velocity / stress, Shields parameter, Rouse number, MOP shoaled\n' ...
    '  reference, currents.\n\n' ...
    'L1 (QC''d raw time series) is regenerable from raw data + this pipeline and\n' ...
    'is not included here to keep the share size manageable.\n\n' ...
    '## Layout\n\n' ...
    '```\n' ...
    'Processed_HLB/\n' ...
    '  README.md\n' ...
    '  manifest.csv      — per-file index (deployment, instrument, depth, time range, sizes)\n' ...
    '  <deployment>/\n' ...
    '    Level2_QC/      — *_L2.mat\n' ...
    '    Level3_QC/      — *_L3.mat\n' ...
    '```\n\n' ...
    '## Conventions\n\n' ...
    '- Coordinate system: x cross-shore (positive onshore), y alongshore (positive north)\n' ...
    '- Vertical: NAVD88 (MSL = 0.774 m, MHW = 1.344 m)\n' ...
    '- Times: UTC, datetime\n' ...
    '- File naming: `<MOP_or_site>_<depth>m_L<N>.mat` (e.g., MOP580_7m_L2.mat)\n\n' ...
    '## RUBY22 vs Ruby2D\n\n' ...
    '- **RUBY22/** is the full processed Ruby2D 2021-2022 cross-shore array at\n' ...
    '  Torrey Pines, ingested via the same pipeline as the rest of the catalog\n' ...
    '  (3 instruments at MOP578 10m, MOP579 6m, MOP582 30m).\n' ...
    '- **Ruby2D/**, if present, contains a single-instrument Level2 reprocess of\n' ...
    '  the legacy archived L1 file, used for the head-to-head validation against\n' ...
    '  the legacy pipeline (`docs/pipeline_comparison_legacy.md` in the source\n' ...
    '  repo). It is not a new deployment.\n\n' ...
    '## CAT21A / CAT21B\n\n' ...
    'Two separate Catalina Island deployments processed through the standard\n' ...
    'pipeline. CAT21A covers Feb-Mar 2021 (CATISL03_*, multi-burst, 117 days);\n' ...
    'CAT21B covers Aug 2021 (CATISL02 single-burst, ~15 days). Catalina is\n' ...
    'outside CDIP MOP coverage, so L2 was processed in buoy coords without\n' ...
    'shore-normal rotation; bulk wave parameters and segment-mean velocity are\n' ...
    'still valid in the buoy frame.\n\n' ...
    '## IB18W / IB19S\n\n' ...
    'Imperial Beach 2018-2019 deployments (south of MOP coverage extent at\n' ...
    'D0045 and D0055), two Vector ADVs deployed cross-shore. Continuous\n' ...
    'record split into a winter sub-deployment (IB18W: 2018-11-27 to\n' ...
    '2019-03-01, ~3 months) and spring (IB19S: 2019-03-01 to 2019-04-23,\n' ...
    '~1.5 months).\n\n' ...
    '## Contact\n\n' ...
    'Holden Leslie-Bole <hlesliebole@ucsd.edu>, Scripps Institution of Oceanography.\n'], ...
    numel(unique(T.deployment)), datestr(now, 'yyyy-mm-dd'), git_hash);
fid = fopen(fullfile(dest_root, 'README.md'), 'w'); fprintf(fid, '%s', readme); fclose(fid);
fprintf('Wrote README.md\n');
